# Generated by Django 6.0.4 on 2026-04-29 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TableResto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('capacity', models.IntegerField()),
                ('table_status', models.IntegerField(default=1)),
                ('status', models.IntegerField(default=1)),
            ],
        ),
    ]
