# Generated by Django 6.0.4 on 2026-04-29 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0002_category_menuresto_statusmodel_delete_tableresto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuresto',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='menuresto',
            name='last_modified',
        ),
    ]
