# Generated by Django 6.0.4 on 2026-04-29 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0003_remove_menuresto_created_on_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='category',
            name='last_modified',
        ),
    ]
